### ISSUE TITLE
docusaurus3.0.1 开发环境可以工作，build后不显示，不报错

### ISSUE THREAD

**Issue by tra4less** [peterroe/docusaurus-plugin-usevue#2]
### Describe the bug

docusaurus3.0.1 开发环境可以工作，build后不显示，不报错

### Reproduction

import test from './test.vue'
import { uvc } from 'use-vue-component' //引入转换包
export const HelloWorld = uvc(x) //转换
return  <Main><HelloWorld/></Main>
### System Info

```Shell
System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M2
    Memory: 88.22 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - /opt/homebrew/bin/npm
  Browsers:
    Safari: 16.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by peterroe** [comment]
两年前写的玩具，已经不维护了，感谢理解～
